### ISSUE TITLE
Out of date CKB balance in the app

### ISSUE THREAD

**Issue by e00dan** [NexisDao/NexisDao-core#2]
![image](https://user-images.githubusercontent.com/4950658/144874877-226c8472-b7ee-4514-9e06-6b8ed12f6baf.png)

https://explorer.nervos.org/aggron/address/ckt1q3vvtay34wndv9nckl8hah6fzzcltcqwcrx79apwp2a5lkd07fdx82lmrfyhl2j3ken652av5trksf2uk9e9c2dm56n

cc @NexisDao

**Comment by e00dan** [comment]
I think `https://rpc-aggron.nexisdao.com/` is not synced.

In the explorer latest block is 3,679,984, but node is responding with 3,514,403

![image](https://user-images.githubusercontent.com/4950658/145050551-bbe38212-0931-48b5-862f-a712f23bdde1.png)

```
➜  / echo '{
    "id": 2,
    "jsonrpc": "2.0",
    "method": "get_tip_block_number",
    "params": []
}' \
| tr -d '\n' \
| curl -H 'content-type: application/json' -d @- \
https://rpc-aggron.nexisdao.com/
{"jsonrpc":"2.0","result":"0x35a023","id":2}
```

**Comment by jordanmack** [comment]
There is a bug in the CKB node that affects the testnet. It should be fixed on v0.101.2.

**Comment by NexisDao** [comment]
Update node to v0.101.2

**Comment by e00dan** [comment]
I confirm it works now 👍
