### ISSUE TITLE
[CRITICAL] Can't convert dCKB to CKB on MAINNET

### ISSUE THREAD

**Issue by e00dan** [NexisDao/NexisDao-core#4]
Backend service: https://dao-lina.nexisdao.com is broken.

Deposit cells aren't displayed in frontend:
![image](https://user-images.githubusercontent.com/4950658/177568717-fd292e94-7e50-4514-b1a0-c3bbb916f15e.png)

**Comment by e00dan** [comment]
cc @NexisDao

**Comment by EthAnalysis** [comment]
have you tried https://app.nexisdao.com/dckb? I see deposit cells and can get dao cells info from explorer but I'm stuck there figuring out how to withdraw my dckb back to ckb. Seems like i keep missing the withdraw window and it keeps staking for another 30 days. https://explorer.nervos.org/transaction/0xa94831899c57c604f1efe594317707ee94b755ce8d23f1c33283770664c6c248
![image](https://user-images.githubusercontent.com/93758917/188906086-ba744b56-a486-45f2-9ff2-677cddc2d660.png)
